<?php

/**
 * @file
 * The main Islandora ETDMS Download module file.
 */

/**
 * Implements hook_islandora_oai_record_alter().
 */
function islandora_etdms_download_islandora_oai_record_alter(&$oai_record, &$params) {
  if ($params['metadata_prefix'] == 'oai_etdms') {
    $dom = new DOMDocument();
    $dom->preserveWhiteSpace = FALSE;
    $dom->formatOutput = TRUE;
    $dom->loadXML($oai_record);
    // Get the CModel, create download link path
    $pid = $params['pid'];
    $object=islandora_object_load($pid);
    $cmodel=$object->models;
    if (in_array('ir:thesisCModel', $object->models) || in_array('ir:citationCModel', $object->models)) {
      global $base_url;
      $fragment = "<identifier>" . $base_url . "/islandora/object/" . $pid . "/datastream/PDF/file.pdf</identifier>";
      $frag = $dom->createDocumentFragment();
      $frag->appendXML($fragment);
      $dom->documentElement->appendChild($frag);
      $oai_record = $dom->saveXML($dom->documentElement);
    }
  }
}
